### PR TITLE
Fix for HP TouchPad Browser.isMobile

### PR DESCRIPTION
**Pull request by dehenne**
Hi cpojer,

i include the HP TouchPad identification the Browser.isMobile attribute.
Because the Browser.Platform.name is linux. Now I check on 'hp-tablet'' in the UA

i think hp-tablet is better then hpwOS 
... i'm not sure, but it can be, that the webOS runs on desktop, too.
so hp-tablet is something unique.

best regards

### CODE REVIEW

**Comment by cpojer** [comment]
What do you think about adding Browser.Device.name == 'touchpad'; and setting Browser.Platform.name to 'webos' and Browser.Platform.webos = true?

I think that would be better.

**Comment by dehenne** [comment]
In addition to the fix? It would be nice if <b>isMobile</b> is true. 
But adding the Browser.Platform.webos and Browser.Device.name makes sense.

I commit a patch for Android and WebOS to the core
https://github.com/dehenne/mootools-core/commit/1d25758f1b4627fe8f3f80081fde082c2aa89710

Maybe we can bring it all together or build on.

**Comment by arian** [comment]
If this ticket https://github.com/mootools/mootools-core/pull/2153 will be resolved, the `isMobile` property will be fixed automagically.

**Comment by dehenne** [comment]
ahhh ... thats true
that happens when you develop with different versions -.-
so sorry

**Pull request closed without merging**
